// <auto-generated />
namespace MoviesWatchList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FixWatchOnstringtodatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixWatchOnstringtodatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201911062047098_Fix WatchOn string to datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
